name:                pyrelude
version:             0.1.0.0
github:              "githubuser/simple-hpack"
license:             MIT
author:              "John Walker"
maintainer:          "theghostjw@gmail.com"
copyright:           "2018 John Walker"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/simple-hpack#readme>

dependencies:
  - base-prelude
  - either
  - exceptions
  - extra
  - hedgehog
  - tasty
  - tasty-hunit
  - tasty-hedgehog
  - text
  - base
  - encode-string
  - containers
  - fmt
  - pretty-show
  - chronos
  - time # need for timezone which is missing from chronos

ghc-options:
  - -fmax-pmcheck-models=100
  - -ferror-spans
  - -O2
  - -Wall
  - -Werror
  - -fprint-potential-instances
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fno-warn-missing-signatures
  - -fno-warn-type-defaults
  - -fno-warn-unused-matches
  - -fno-warn-unused-binds
  - -fno-warn-unused-imports

default-extensions:
  - AllowAmbiguousTypes
  - BangPatterns
  # - BlockArguments
  - ConstrainedClassMethods
  - ConstraintKinds
  - DisambiguateRecordFields
  - DuplicateRecordFields
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - ExistentialQuantification
  - ExtendedDefaultRules
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - ImportQualifiedPost
  - KindSignatures
  - LambdaCase
  - LiberalTypeSynonyms
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternSynonyms
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators

library:
  source-dirs: src
  other-modules:
    - Debug.Trace.Extended
    - Language.Haskell.TH.Syntax.Extended
    - Path.Extended
    - Path.IO.Extended
    - Pyrelude.Test.Hedgehog.Extended
    - Pyrelude.Test.Tasty.HUnit.Extended
    - Stringy
    - Ternary
    - Listy
  dependencies:
    - path # - version set in extra deps - until can roll forward
    - path-io # - version set in extra deps - until ide supports later version of haskell
    - bytestring
    - template-haskell
    - discrimination
    - old-locale

tests:
  pyrelude-test:
    main:                driver.hs
    source-dirs:         test
    dependencies:
      - pyrelude
      - tasty-discover
      - mtl
