name: pyrethrum-extras
version: 0.1.0.0
github: "githubuser/simple-hpack"
license: MIT
author: "John Walker"
maintainer: "theghostjw@gmail.com"
copyright: "2018 John Walker"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/simple-hpack#readme>

dependencies:
  - base
  - base-prelude
  - containers
  - chronos
  - either
  - encode-string
  - exceptions
  - extra
  - filepath
  - hedgehog
  - pretty-show
  - tasty
  - tasty-hunit
  - tasty-hedgehog
  - text
  - time
  # - fmt
  # - time # need for timezone which is missing from chronos
  # - Win32

ghc-options:
  - -fmax-pmcheck-models=10000000
  - -ferror-spans
  - -O2
  - -Wall
  - -Werror
  - -fprint-potential-instances
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -fno-warn-type-defaults
  - -fno-warn-unused-matches
  - -fno-warn-unused-binds
  - -Wno-unused-do-bind

default-extensions:
  - AllowAmbiguousTypes
  - BangPatterns
  - BlockArguments
  - ConstrainedClassMethods
  - ConstraintKinds
  - DisambiguateRecordFields
  - DuplicateRecordFields
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - ExistentialQuantification
  - ExtendedDefaultRules
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - ImportQualifiedPost
  - KindSignatures
  - LambdaCase
  - LiberalTypeSynonyms
  - OverloadedRecordDot
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - NoFieldSelectors
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternSynonyms
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators

library:
  source-dirs: src
  exposed-modules:
    - Debug.Trace.Extended
    - Language.Haskell.TH.Syntax.Extended
    - Path.Extended
    - Path.IO.Extended
    - PyrethrumExtras
    - PyrethrumExtras.IO
    - PyrethrumExtras.Test
    - PyrethrumExtras.Test.Hedgehog.Extended
    - PyrethrumExtras.Test.Tasty.HUnit.Extended
    - Stringy
    - Ternary
    - Listy
  dependencies:
    - path # - version set in extra deps - until can roll forward
    - path-io # - version set in extra deps - until ide supports later version of haskell
    - bytestring
    - template-haskell
    - discrimination
    - old-locale
    - pretty-show

tests:
  pyrelude-test:
    main: driver.hs
    source-dirs: test
    dependencies:
      - pyrethrum-extras
      - tasty-discover
      - mtl
    build-tools: tasty-discover:tasty-discover
